version: '3.3'
services:
  fluentd:
    image: fluentd-influxdb
    build: ./fluentd
    links:
      - influxdb
    networks:
      - external_network
      - logging_stuff_network
    ports:
      - '24224:24224'
      - '5140:5140/tcp'
      - '5140:5140/udp'
    volumes:
      - './fluentd/configs/:/fluentd/etc/'
  influxdb:
    image: influxdb:1.7.4
    ports:
      - '8086:8086'
    networks:
      - logging_stuff_network
    env_file:
      - influx/influx.env
    volumes:
      - './influx/internal:/var/lib/influxdb'
  chronograf:
    image: chronograf:latest
    links:
      - influxdb
    networks:
      - logging_stuff_network
      - applications_network
    env_file:
      - chronograf/chronograf.env
    ports:
      - "8888:8888"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - applications_network
      - external_network
    links:
      - fluentd
    restart: unless-stopped
    logging:
      driver: 'fluentd'
      options:
        tag: nginx
        fluentd-async-connect: 'true'
        fluentd-max-retries: '20'
  web:
    build: ./flask
    ports:
      - "3000:3000"
    networks:
      - applications_network
    links:
      - nginx
      - fluentd
    restart: unless-stopped
    logging:
      driver: 'fluentd'
      options:
        tag: python
        fluentd-async-connect: 'true'
        fluentd-max-retries: '20'

networks:
  logging_stuff_network:
    internal: true
    driver: bridge
  applications_network:
    internal: true
    driver: bridge
  external_network:
     #default network with internet access
