version: '3'
services:
  influxdb:
    image: influxdb:1.7.4
    ports:
      - '8086:8086'
    networks:
      - logging_stuff
    environment:
      - INFLUXDB_DB=test
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - './data:/var/lib/influxdb'
  chronograf:
    image: chronograf:1.3.8
    links:
      - influxdb
    networks:
      - external_nw
      - logging_stuff
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_DB=test
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=admin
    ports:
      - "8888:8888"

  fluentd:
    image: fluentd-influxdb
    build: ./fluentd
    links:
      - influxdb
    networks:
      - logging_stuff
    ports:
      - '24224:24224'
      - "24224:24224/udp"
    volumes:
      - './fluentd/fluent.conf:/fluentd/etc/fluent.conf'
      - './logs/:/var/log/'
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - fluentd
    networks:
      - internal_nw
      - external_nw
      - logging_stuff
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: fluentd:24224
        tag: web.nginx
        fluentd-async-connect: 'true'
        fluentd-max-retries: '10'
  web:
    build: ./flask
    ports:
      - "3000:3000"
    links:
      - fluentd
    networks:
      - internal_nw
      - logging_stuff
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: fluentd:24224
        tag: web.python
        fluentd-async-connect: 'true'
        fluentd-max-retries: '10'


networks:
  logging_stuff:
    internal: true
    driver: bridge
  internal_nw:
    internal: true
    driver: bridge
  external_nw:
     #default network with internet access
